### ISSUE TITLE
In-memory filesystem "mv" fails with KeyError on src directory

### ISSUE THREAD

**Issue by jorisvandenbossche** [intake/filesystem_spec#316]
It's not fully clear if this is supposed to work. The spec docs mention "move file" https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.mv, but in general (eg `mv` bash command) `mv` also works for directories, and also the fsspec LocalFileSystem moves directories. 

Or, if not `mv`, what's the method in the spec to copy directories? (I think `copy` is meant to be limited to files?)

```
In [1]: import fsspec                                                                                                                                                                                              

In [2]: memfs = fsspec.filesystem("memory")                                                                                                                                                                        

In [3]: memfs.mkdir("src")                                                                                                                                                                                         

In [4]: memfs.touch("src/file.txt")                                                                                                                                                                                

In [5]: memfs.mv("src", "dest")                                                                                                                                                                                    
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-2fbbb45834de> in <module>
----> 1 memfs.mv("src", "dest")

~/scipy/repos/filesystem_spec/fsspec/spec.py in mv(self, path1, path2, **kwargs)
    668     def mv(self, path1, path2, **kwargs):
    669         """ Move file from one location to another """
--> 670         self.copy(path1, path2, **kwargs)
    671         self.rm(path1, recursive=False)
    672 

~/scipy/repos/filesystem_spec/fsspec/implementations/memory.py in copy(self, path1, path2, **kwargs)
    129 
    130     def copy(self, path1, path2, **kwargs):
--> 131         self.store[path2] = MemoryFile(self, path2, self.store[path1].getbuffer())
    132 
    133     def cat(self, path):

KeyError: 'src'

In [6]: memfs.info("src")                                                                                                                                                                                          
Out[6]: {'name': 'src/', 'size': 0, 'type': 'directory'}
```

**Comment by jorisvandenbossche** [comment]
Was this fixed, or is it an invalid report?

**Comment by martindurant** [comment]
Should be fixed on master, I think. Sneaked in with another PR, but please do check.

**Comment by jorisvandenbossche** [comment]
The example above is still failing:

```
In [2]: memfs.mv("src", "dest")   
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-f19385573340> in <module>
----> 1 memfs.mv("src", "dest")

~/scipy/repos/filesystem_spec/fsspec/spec.py in mv(self, path1, path2, recursive, maxdepth, **kwargs)
    742         """ Move file(s) from one location to another """
    743         self.copy(path1, path2, recursive=recursive, maxdepth=maxdepth)
--> 744         self.rm(path1, recursive=recursive)
    745 
    746     def rm_file(self, path):

~/scipy/repos/filesystem_spec/fsspec/spec.py in rm(self, path, recursive, maxdepth)
    765         path = self.expand_path(path, recursive=recursive, maxdepth=maxdepth)
    766         for p in reversed(path):
--> 767             self._rm(p)
    768 
    769     @classmethod

~/scipy/repos/filesystem_spec/fsspec/implementations/memory.py in _rm(self, path)
    147             del self.store[path]
    148         elif self.isdir(path):
--> 149             self.rmdir(path)
    150         else:
    151             raise FileNotFoundError

~/scipy/repos/filesystem_spec/fsspec/implementations/memory.py in rmdir(self, path)
     96                 self.pseudo_dirs.remove(path)
     97             else:
---> 98                 raise OSError("Directory %s not empty" % path)
     99         else:
    100             raise FileNotFoundError(path)

OSError: Directory src not empty
```

Now, there seems to be a `recursive` keyword, and with specifying that it works:

```
In [4]: memfs.mv("src", "dest", recursive=True) 
```

But, with a local filesystem, specifying that keyword is not needed, and it works with `mv("src", "dest")` out of the box (also, the `recursive` keyword is not documented)

**Comment by martindurant** [comment]
Agree that the API should match and be well documented. I'm not sure that in the local case there is a way to avoid recursive, at least not with the standard library (but I could check for the case).

**Comment by jorisvandenbossche** [comment]
So to get a confirmation here: is `mv` supposed to work for directories or does this need the `recursive` keyword? Because as noted above, this actually worked out of the box with the LocalFileSystem without any keyword.

**Comment by martindurant** [comment]
I think that `recursive` ought to be required, yes. The local FS is special, in that you can move a whole directory tree in a single operation; that's not possible in most implementations.
